language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_install:
  - composer update # Use update since we'll be changing the composer.json

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpcs --standard=PSR2 src